name       : clicompanion
version    : 1.1
release    : 2
source     :
    - https://solus-project.com/sources/clicompanion-1.1.tar.xz : 6f708717f7d5de0ef7439564fdd143db7a35ac6825e8a95e4bd78545c2103448
license    : GPL-3.0
summary    : CLI Companion is a Terminal that lets you store commands and create a 'command dictionary.'
description: |
    CLI Companion is a tool to store and run Terminal commands from a GUI. People unfamiliar with the Terminal will find CLI Companion a useful way to become acquainted with the Terminal and unlock its potential. Experienced users can use CLI Companion to store their extensive list of commands in a searchable list.
builddeps  :
    - python-distutils-extra
    - pkgconfig(pyvte)
rundeps    :
    - python-gtk2
    - vte2
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
